directory: "./surface"
dictionary_cubes: "./boxes/"
prism_types: ["realsense", "tplink", "corsair", "3060"]
num_instances: 20
# WARNING: if output_dir ends with "-r", the directory will be removed if it already exists
# output_dir: "./synthetic_data-r"
output_dir: "./synthetic_data"
maxtries: 50
assets: "./objs_meshes/"
min_width_bbox: 2.0
min_height_bbox: 3.5
min_instances_accepted: 3
min_box_coverage: 33
img_width: 640
img_height: 640
camera_position:
  - [-0.5, 0.5, 2.0]
  - [0.4, -1.7, 2.0]
  - [1.0, 0.4, 2.0]
  - [1.05, 2.2, 2.0]
  - [0.5, 1.5, 1.75]
camera_rotation_constraints:
  - [20, 50, -20, 5, 140, 160]
  - [30, 45, -15, 15, 50, 110]
  - [40, 60, -10, 10, 30, 110]
  - [50, 70, -10, 10, 70, 120]
  - [30, 50, -10, 5, 30, 100]
focal_length_constraints:
  - [30, 50]
  - [30, 40]
  - [40, 50]
  - [40, 60]
  - [20, 40]
lightning_constraints:
  - ["POINT", -0.5, -2.0, 2.75, 1, 3]
  - ["POINT", 0.9, -2.0, 2.75, 1, 3]
  - ["POINT", -0.5, -0.25, 2.75, 1, 3]
  - ["POINT", 0.8, -0.25, 2.75, 1, 3]
  - ["POINT", -0.5, 1.5, 2.75, 1, 3]
  - ["POINT", 0.8, 1.5, 2.75, 1, 3]
# You must choose one of the following parameters. Comment out the one you do not use.
# min_instances: X -> Valid images are generated until all classes have at least X instances in total.
# total_images: Y -> Y valid images are generated regardless of the number of instances per class.
#min_instances: 7500
total_images: 5
